sudo: required
dist: trusty
language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install xutils-dev doxygen libxcb-xkb-dev

compiler:
    - gcc
    - clang

script:
    - mkdir autotools-build && cd autotools-build && ../autogen.sh && make && make check
